# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=40)),
                ('common_name', models.CharField(max_length=25)),
                ('current_population', models.IntegerField(default=0)),
                ('historic_population', models.IntegerField(default=0)),
                ('historic_year', models.IntegerField(default=0)),
                ('percent_decline', models.DecimalField(decimal_places=2, max_digits=5)),
                ('native_range', models.CharField(max_length=5)),
                ('last_updated', models.DateTimeField(verbose_name='date')),
                ('sci_kingdom', models.CharField(max_length=30)),
                ('sci_phylum', models.CharField(max_length=30)),
                ('sci_class', models.CharField(max_length=30)),
                ('sci_order', models.CharField(max_length=30)),
                ('sci_family', models.CharField(max_length=30)),
                ('pop_trend', models.CharField(max_length=4)),
                ('upper_weight', models.IntegerField(default=0)),
                ('weight_units', models.CharField(max_length=12)),
            ],
        ),
    ]
